### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Sannis** [Sannis/node-mysql-libmysqlclient#148]

**Comment by chenming142** [comment]
@jaxbot  I need you help for mysql-libmysqlclient on windows.so you can share me.
my email is chenming142@sina.com.
this url:http://www.godchaos.com/mysql-libmysqlclient.7z is not valid.

**Comment by tengattack** [comment]
@chenming142  New URL here (old version, only for dev environment): https://bless.moe/io/node/win/mysql-libmysqlclient.7z
