### ISSUE TITLE
npm install mysql-libmysqlclient ERROR on Mac OS X

### ISSUE THREAD

**Issue by hdwong** [Sannis/node-mysql-libmysqlclient#178]
When I install mysql-libmysqlclient on Mac OS X 10.8.5, npm throw some errors:

> npm install mysql-libmysqlclient
> npm http GET https://registry.npmjs.org/mysql-libmysqlclient
> npm http 200 https://registry.npmjs.org/mysql-libmysqlclient
> 
> mysql-libmysqlclient@1.5.2 install [my home path]/node_modules/mysql-libmysqlclient
> node-gyp rebuild
> 
> gyp: [my home path]/.node-gyp/0.10.17/common.gypi not found (cwd: [my home path]/node_modules/mysql-libmysqlclient) while reading includes of binding.gyp while trying to load binding.gyp
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:424:16)
> gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
> gyp ERR! System Darwin 12.5.0
> gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd [my home path]/node_modules/mysql-libmysqlclient
> gyp ERR! node -v v0.10.17
> gyp ERR! node-gyp -v v0.10.9
> gyp ERR! not ok 
> npm ERR! weird error 1
> npm ERR! not ok code 0

**Comment by lozanet2005** [comment]
So what's the solution?
