### ISSUE TITLE
Getting gyp: Call to 'mysql_config --cflags' returned exit status 1 error while running npm install mapper 

### ISSUE THREAD

**Issue by sosuri** [Sannis/node-mysql-libmysqlclient#189]
Getting below stack-trace while executing npm install mapper:

'mysql_config' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'mysql_config --cflags' returned exit status 1. while trying to loa
d binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd D:\New folder (2)\node_modules\mapper\node_modules\mysql-libmysqlcl
ient
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs
\node_modules\npm\bin\npm-cli.js" "install" "mapper"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! mysql-libmysqlclient@1.5.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mysql-libmysqlclient@1.5.2 install script 'node-gyp rebui
ld'.
npm ERR! This is most likely a problem with the mysql-libmysqlclient package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mysql-libmysqlclient
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\New folder (2)\npm-debug.log

Not sure how to resolve this issue, requesting for help!!!!!!

**Comment by coolguy001tv** [comment]
the same problem happened on me. I am using Win7 .

**Comment by Sannis** [comment]
@sosuri @coolguy001tv, you must install mysql-devel or similar package on *nix or build and install MySQL from sources with development headers on other OS-es. After that you should ensure that mysql_config in in $PATH and you can call it in terminal.
