### ISSUE TITLE
run error on node v0.11.10

### ISSUE THREAD

**Issue by wangbinlml** [Sannis/node-mysql-libmysqlclient#191]
I am using Ubuntu or Centos, and this module had compiled successfully on node v0.11.10,  when I run Query program,it throw the following error:

**node: symbol lookup error: /root/mm_core/node_modules/mysql-libmysqlclient/build/Release/mysql_bindings.node: undefined symbol: _ZN2v84TrueEv**

Please help me. Ths.

**Comment by Sannis** [comment]
Will be fixed in #192.
